
/* Main.c file generated by New Project wizard
 *
 * Created:   dv. oct. 17 2025
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#include <stdlib.h>
#include "config.h"

#define _XTAL_FREQ 8000000

// VARIABLES GLOBALES:
int num[4] = {0,0,0,0};
int sort = 0; // Para INT0 (saber si genera un rand num [0] o lo ordena [1])


void configPIC(){
	T0CON = 0b10000111;
   // Todos los puertos a digital:
   ANSELA = 0;
   ANSELB = 0;
   ANSELD = 0;
   
   // Puertos de output:
   TRISA = 0;
   TRISD = 0;
   
   // Puertos de input:
   TRISB = 0xFF;

   // Interrupts:
      // GENERAL 
   GIE = 1;
   GIEL = 1;
   IPEN = 1;

      //ENABLE INT0
   INTCONbits.INT0IE = 1; 
   INTCON3bits.INT1IE = 0;
   INTCON3bits.INT2IE = 0;

      //CONFIG PRIO
   INTCON3bits.INT1IP = 0;
   INTCON3bits.INT2IP = 0;
   
      // CLEAN FLAGS
   INTCONbits.INT0IF = 0;
   INTCON3bits.INT1IF = 0;
   INTCON3bits.INT2IF = 0;

      // FLANC CONFIG
   INTCON2bits.INTEDG0 = 1; 
   INTCON2bits.INTEDG1 = 0;
   INTCON2bits.INTEDG2 = 0;
 

}

void display(int digit, int valor) {
   // Elegimos el display a encender:
   LATA = 1 << (digit-1);
   // Le asignamos el valor:
   LATD = valor;

   __delay_us(1);
}

int comp(const void *elem1, const void *elem2) {
	int a = *(const int *) elem1;
	int b = *(const int *) elem2;
    return (a < b) - (a > b);
}


void interrupt int_func_HighP() { // Tiempo de interrupción entre 0.001413 y 0.001640 segundos
   if (INTCONbits.INT0IE && INTCONbits.INT0IF) { 
      if (!sort) { 
			// Select numero random en tre 0 y 9999 
         int seed = TMR0;
         srand(seed);
         int aux = rand() % 10000;
         for (int i = 0; i < 4; i++) {
            num[3 - i] = aux % 10;
            aux /= 10;
         }
      } else {
         qsort(num, 4, sizeof(int), comp);
      }
      INTCONbits.INT0IF = 0;
      INTCON3bits.INT1IE = !sort;
      INTCON3bits.INT2IE = !sort;
      sort = !sort;
   }
}


void interrupt low_priority int_func_LowP(){
   if (INTCON3bits.INT1IE && INTCON3bits.INT1IF) {
      int aux = num[3];
      for (int i = 2; i >= 0; i--) {
            num[i + 1] = num[i];
      }
      num[0] = aux;
      INTCON3bits.INT1IF = 0;
   }
   
   if (INTCON3bits.INT2IE && INTCON3bits.INT2IF) {
      int aux = num[0];
      for (int i = 0; i < 3; i++) {
         num[i] = num[i + 1];
      }
      num[3] = aux;
      INTCON3bits.INT2IF = 0;
   }
}

void main(void)
{
   configPIC();
   // Inicializamos variables
   int segment_config [10] = {
		0x3F, // 0 
		0x06, // 1 
		0x5B, // 2
		0x4F, //3
		0x66, //4
		0x6D, //5
		0x7D, //6
		0x07, //7
		0x7F, //8
		0x6F, //9
	};
    
   // Write your code here
   while (1) {
      // Mostramos los numeros en el 7SEG_DISPLAY
      for (int i = 1; i <= 4; ++i) {
         display(i, segment_config[num[i-1]]);
      }
   }
	// Frequencia limite:
	// Antes de que se muestre todo 8: 40
}